# Generated by Django 5.0.6 on 2024-06-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_taskapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAPI',
        ),
    ]
